AllCops:
  TargetRubyVersion: 2.3
  Include:
    - Rakefile
  Exclude:
    - Gemfile

Style/SymbolArray:
  EnforcedStyle: brackets
Style/LineLength:
  Max: 180
Style/ClassAndModuleChildren:
  EnforcedStyle: compact
Style/FileName:
  Exclude:
    - '**/mockserver-client.rb'
    - 'mockserver-client.gemspec'
